<a href="https://colab.research.google.com/github/arturgmrs/integraschoolpython/blob/master/ex01_extrair_dados_de_pdf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aplicação para extrair dados de páginas web usando [Tabula](https://github.com/chezou/tabula-py)

In [ ]:
# instalar o pacote tabula no python
pip install tabula-py

In [ ]:
import tabula

tabula.environment_info()

Python version:
    3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0]
Java version:
    openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
tabula-py version: 2.1.1
platform: Linux-4.19.104+-x86_64-with-Ubuntu-18.04-bionic
uname:
    uname_result(system='Linux', node='c2c91e04de91', release='4.19.104+', version='#1 SMP Wed Feb 19 05:26:34 PST 2020', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '18.04', 'bionic')
mac_ver: ('', ('', '', ''), '')

In [ ]:
# fonte do pdf
pdf_path = "http://www.comperve.ufrn.br/conteudo/metropoledigital/2020/documentos/lista_aprovados_terceira_chamada_20200131.pdf"

# Opções de configuração da página para leitura, no exemplo é lida a página 3 do edital
tabula.read_pdf(pdf_path, pages=3, stream=True)[0]

Got stderr: Jun 28, 2020 1:48:25 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font Symbol
Jun 28, 2020 1:48:25 AM org.apache.pdfbox.pdmodel.font.PDType1Font <init>
WARNING: Using fallback font LiberationSans for base font ZapfDingbats

   Unnamed: 0  ...                Unnamed: 3
0   INSCRIÇÃO  ...                  SITUAÇÃO
1         NaN  ...                       NaN
2   540032271  ...        CANDIDATO APROVADO
3   540021555  ...        CANDIDATO APROVADO
4   540019550  ...        CANDIDATO APROVADO
5   540017388  ...        CANDIDATO APROVADO
6   540014192  ...        CANDIDATO APROVADO
7   540032336  ...        CANDIDATO APROVADO
8   540025135  ...        CANDIDATO APROVADO
9   540005746  ...        CANDIDATO APROVADO
10  540026905  ...        CANDIDATO APROVADO
11  540001104  ...        CANDIDATO APROVADO
12  540020281  ...        CANDIDATO APROVADO
13  540031771  ...        CANDIDATO APROVADO
14  540017973  ...        CANDIDATO APROVADO
15        NaN  ...  CANDIDATO APROVADO ACIMA
16  540009466  ...        DO NÚMERO DE VAGAS
17        NaN  ...                (SUPLENTE)
18        NaN  ...  CANDIDATO APROVADO ACIMA
19  540008184  ...        DO NÚMERO DE VAGAS
20        NaN  ...                (SUPLENTE)
21        NaN  ...  CANDIDATO APROVADO ACIMA
22  540029033  ...        DO NÚMERO DE VAGAS
23        NaN  ...                (SUPLENTE)
24        NaN  ...  CANDIDATO APROVADO ACIMA
25  540032042  ...        DO NÚMERO DE VAGAS
26        NaN  ...                (SUPLENTE)

[27 rows x 6 columns]